// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"skyrix/internal/commands"
	"skyrix/internal/engine"
	jobs2 "skyrix/internal/jobs"
	"skyrix/internal/kernel"
	"skyrix/internal/kernel/jobs"
	"skyrix/internal/providers"
)

// Injectors from wire.go:

func buildConsoleApp() (*kernel.ConsoleApp, func(), error) {
	config, err := kernel.ProvideConfig()
	if err != nil {
		return nil, nil, err
	}
	logger := kernel.ProvideLoggerConfig(config)
	loggerInterface := kernel.ProvideLogger(logger)
	database := kernel.ProvideDatabaseConfig(config)
	db, cleanup, err := kernel.ProvidePostgres(database, loggerInterface)
	if err != nil {
		return nil, nil, err
	}
	engineDatabase := engine.ProvideDatabaseService(db, config)
	redis := kernel.ProvideRedisConfig(config)
	client, cleanup2, err := kernel.ProvideRedis(redis, loggerInterface)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	engineRedis := engine.ProvideRedisService(client, loggerInterface, config)
	registry := jobs.NewRegistry(loggerInterface)
	kernelKernel := kernel.NewKernel(config, loggerInterface, engineDatabase, engineRedis, registry)
	systemPingJob := jobs2.NewSystemPingJob(loggerInterface)
	providersJobs := &providers.Jobs{
		SystemPingJob: systemPingJob,
	}
	helloCommand := commands.NewHelloCommand()
	providersCommands := providers.ProvideCommands(helloCommand)
	consoleApp := kernel.NewConsoleApp(kernelKernel, providersJobs, providersCommands)
	return consoleApp, func() {
		cleanup2()
		cleanup()
	}, nil
}
