// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"skyrix/internal/commands"
	"skyrix/internal/database"
	"skyrix/internal/engine"
	"skyrix/internal/engine/scaffold/console"
	"skyrix/internal/engine/scaffold/db"
	"skyrix/internal/engine/scaffold/eventbus"
	"skyrix/internal/engine/scaffold/job"
	make2 "skyrix/internal/engine/scaffold/make"
	jobs2 "skyrix/internal/jobs"
	"skyrix/internal/kernel"
	"skyrix/internal/kernel/jobs"
	"skyrix/internal/providers"
)

// Injectors from wire.go:

func buildConsoleApp() (*kernel.ConsoleApp, func(), error) {
	config, err := kernel.ProvideConfig()
	if err != nil {
		return nil, nil, err
	}
	loggerInterface := kernel.ProvideLogger(config)
	configDatabase := kernel.ProvideDatabaseConfig(config)
	gormDB, cleanup, err := kernel.ProvidePostgres(configDatabase, loggerInterface)
	if err != nil {
		return nil, nil, err
	}
	engineDatabase := engine.ProvideDatabaseService(gormDB, config)
	redis := kernel.ProvideRedisConfig(config)
	client, cleanup2, err := kernel.ProvideRedis(redis, loggerInterface)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	engineRedis := engine.ProvideRedisService(client, loggerInterface, config)
	registry := jobs.NewRegistry(loggerInterface)
	systemPingJob := jobs2.NewSystemPingJob(loggerInterface)
	providersJobs := &providers.Jobs{
		SystemPingJob: systemPingJob,
	}
	jobsRegistry := providers.ProvideRegisteredJobsRegistry(registry, providersJobs)
	kernelKernel := kernel.NewKernel(config, loggerInterface, engineDatabase, engineRedis, jobsRegistry)
	helloCommand := commands.NewHelloCommand()
	dbSeeder := database.NewDBSeeder(engineDatabase, loggerInterface)
	dbMigrator := database.NewDBMigrator(engineDatabase, loggerInterface, dbSeeder)
	dbAutoMigrateCommand := db.NewDBAutoMigrateCommand(dbMigrator)
	dbSeedCommand := db.NewDBSeedCommand(dbSeeder)
	dbCommand := db.NewDBCommand(dbAutoMigrateCommand, dbSeedCommand)
	jobsRunCommand := job.NewJobsRunCommand(jobsRegistry)
	eventBusCommand := eventbus.NewEventBusCommand()
	makeCommand := make2.NewMakeCommand()
	consoleCommands := console.NewCommands(helloCommand, dbCommand, jobsRunCommand, eventBusCommand, makeCommand)
	consoleApp := kernel.NewConsoleApp(kernelKernel, providersJobs, consoleCommands)
	return consoleApp, func() {
		cleanup2()
		cleanup()
	}, nil
}
