// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gitlab.com/skyrix-lib/eventbus"
	"skyrix/internal/domain/example/repository"
	"skyrix/internal/domain/example/services"
	"skyrix/internal/domain/example/unitOfWork"
	"skyrix/internal/engine"
	"skyrix/internal/handlers"
	jobs2 "skyrix/internal/jobs"
	"skyrix/internal/kernel"
	"skyrix/internal/kernel/jobs"
	"skyrix/internal/middleware"
	"skyrix/internal/providers"
	"skyrix/internal/router"
	"skyrix/internal/transport/nats/v1"
	"skyrix/internal/validation"
)

// Injectors from wire.go:

func buildHTTPApp() (*kernel.HTTPApp, func(), error) {
	config, err := kernel.ProvideConfig()
	if err != nil {
		return nil, nil, err
	}
	httpServer := kernel.ProvideHttpServerConfig(config)
	manyRequestsMiddleware := middleware.NewManyRequestsMiddleware()
	loggerInterface := kernel.ProvideLogger(config)
	recoverMiddleware := middleware.NewRecoverMiddleware(loggerInterface)
	gzipDecompressMiddleware := middleware.NewGzipDecompressMiddleware(loggerInterface)
	jwt := kernel.ProvideJWTConfig(config)
	authMiddleware := middleware.NewAuthMiddleware(loggerInterface, jwt)
	globalMiddleware := &providers.GlobalMiddleware{
		ManyRequests:   manyRequestsMiddleware,
		Recover:        recoverMiddleware,
		GzipDecompress: gzipDecompressMiddleware,
		Auth:           authMiddleware,
	}
	noopTenantMiddleware := router.NewNoopTenantMiddleware()
	validator := validation.NewValidator()
	database := kernel.ProvideDatabaseConfig(config)
	db, cleanup, err := kernel.ProvidePostgres(database, loggerInterface)
	if err != nil {
		return nil, nil, err
	}
	engineDatabase, err := engine.ProvideDatabaseService(db, config)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	taskRepository := repository.NewTaskRepository(engineDatabase)
	createTaskUOW := unitofwork.NewCreateTaskUnitOfWork(engineDatabase, taskRepository)
	taskService := services.NewTaskService(taskRepository, createTaskUOW)
	exampleTaskHandler := handlers.NewExampleTaskHandler(loggerInterface, validator, taskService)
	providersHandlers := &providers.Handlers{
		ExampleTask: exampleTaskHandler,
	}
	handler := router.ProvideRouter(httpServer, globalMiddleware, noopTenantMiddleware, providersHandlers)
	server := kernel.ProvideHTTPServer(handler, httpServer)
	redis := kernel.ProvideRedisConfig(config)
	client, cleanup2, err := kernel.ProvideRedis(redis, loggerInterface)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	engineRedis := engine.ProvideRedisService(client, loggerInterface, config)
	registry := jobs.NewRegistry(loggerInterface)
	systemPingJob := jobs2.NewSystemPingJob(loggerInterface)
	providersJobs := &providers.Jobs{
		SystemPingJob: systemPingJob,
	}
	jobsRegistry := providers.ProvideRegisteredJobsRegistry(registry, providersJobs)
	kernelKernel := kernel.NewKernel(config, loggerInterface, engineDatabase, engineRedis, jobsRegistry)
	queue := providers.ProvideQueueConfig(config)
	v := providers.ProvideEventBusConfig(queue)
	v2 := providers.ProvideEventBusLogger(loggerInterface)
	v3, cleanup3, err := eventbus.ProvideBus(v, v2)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	subscriberGroup := v1.NewSubscriberGroup(v3)
	runtime := providers.ProvidePlatformRuntime(subscriberGroup)
	httpApp, err := kernel.NewHTTPApp(server, kernelKernel, runtime)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return httpApp, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
