// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"skyrix/internal/domain/subscriber/repository"
	"skyrix/internal/domain/subscriber/services"
	"skyrix/internal/engine"
	"skyrix/internal/engine/tenantPackage"
	"skyrix/internal/handlers"
	"skyrix/internal/kernel"
	"skyrix/internal/kernel/jobs"
	"skyrix/internal/middleware"
	"skyrix/internal/providers"
	"skyrix/internal/router"
	"skyrix/internal/validation"
)

// Injectors from wire.go:

func buildHTTPApp() (*kernel.HTTPApp, func(), error) {
	config, err := kernel.ProvideConfig()
	if err != nil {
		return nil, nil, err
	}
	httpServer := kernel.ProvideHttpServerConfig(config)
	manyRequestsMiddleware := middleware.NewManyRequestsMiddleware()
	logger := kernel.ProvideLoggerConfig(config)
	loggerInterface := kernel.ProvideLogger(logger)
	recoverMiddleware := middleware.NewRecoverMiddleware(loggerInterface)
	gzipDecompressMiddleware := middleware.NewGzipDecompressMiddleware(loggerInterface)
	globalMiddleware := &providers.GlobalMiddleware{
		ManyRequests:   manyRequestsMiddleware,
		Recover:        recoverMiddleware,
		GzipDecompress: gzipDecompressMiddleware,
	}
	noopTenantMiddleware := router.NewNoopTenantMiddleware()
	database := kernel.ProvideDatabaseConfig(config)
	db, cleanup, err := kernel.ProvidePostgres(database, loggerInterface)
	if err != nil {
		return nil, nil, err
	}
	engineDatabase := engine.ProvideDatabaseService(db, config)
	string2 := tenantPackage.ProvideTenantHeader(config)
	subscriberRepository := repository.NewSubscriberRepository(engineDatabase, string2, loggerInterface)
	subscriberService := services.NewSubscriberService(subscriberRepository, loggerInterface)
	validator := validation.NewValidator()
	subscriberHandler := handlers.NewSubscriberHandler(loggerInterface, subscriberService, validator)
	providersHandlers := &providers.Handlers{
		Subscriber: subscriberHandler,
	}
	handler := router.ProvideRouter(httpServer, globalMiddleware, noopTenantMiddleware, providersHandlers)
	server := kernel.ProvideHTTPServer(handler, httpServer)
	redis := kernel.ProvideRedisConfig(config)
	client, cleanup2, err := kernel.ProvideRedis(redis, loggerInterface)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	engineRedis := engine.ProvideRedisService(client, loggerInterface, config)
	registry := jobs.NewRegistry(loggerInterface)
	kernelKernel := kernel.NewKernel(config, loggerInterface, engineDatabase, engineRedis, registry)
	httpApp, err := kernel.NewHTTPApp(server, kernelKernel)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return httpApp, func() {
		cleanup2()
		cleanup()
	}, nil
}
