package eventbus

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"skyrix/internal/engine/scaffold/support"

	"github.com/spf13/cobra"
)

const (
	eventBusGeneratedHeader = "// Code generated by skyrix eventbus command. DO NOT EDIT."
	eventBusModuleMarker    = ".skyrix-eventbus-module"
)

// EventBusCommand manages EventBus transport scaffolding.
type EventBusCommand struct {
	ProjectRoot string
}

// NewEventBusCommand constructs the EventBus scaffolding command.
func NewEventBusCommand() *EventBusCommand {
	return &EventBusCommand{ProjectRoot: "."}
}

// ToCobraCommand converts EventBusCommand into a Cobra command tree.
func (c *EventBusCommand) ToCobraCommand() *cobra.Command {
	command := &cobra.Command{
		Use:     "eventbus",
		Aliases: []string{"bus"},
		Short:   "Manage EventBus transport scaffolding",
	}
	command.AddCommand(
		&cobra.Command{
			Use:   "init",
			Short: "Initialize EventBus transport scaffolding",
			Args:  cobra.NoArgs,
			RunE: func(cmd *cobra.Command, _ []string) error {
				root, err := support.ProjectRoot(c.ProjectRoot)
				if err != nil {
					return err
				}
				transportRoot := eventBusTransportRoot(root)
				if _, err := os.Stat(transportRoot); err == nil {
					return fmt.Errorf("eventbus transport is already initialized: %s", transportRoot)
				} else if !os.IsNotExist(err) {
					return fmt.Errorf("inspect eventbus transport: %w", err)
				}
				if err := os.MkdirAll(transportRoot, 0o755); err != nil {
					return fmt.Errorf("create eventbus transport directory: %w", err)
				}
				if err := c.writeEventBusRegistration(root); err != nil {
					_ = os.RemoveAll(transportRoot)
					return err
				}
				fmt.Fprintf(cmd.OutOrStdout(), "eventbus initialized: %s\n", transportRoot)
				return nil
			},
		},
		&cobra.Command{
			Use:   "create <Name>",
			Short: "Create an EventBus transport module",
			Args:  cobra.ExactArgs(1),
			RunE: func(cmd *cobra.Command, args []string) error {
				name, err := support.NormalizeName(args[0])
				if err != nil {
					return err
				}
				root, err := support.ProjectRoot(c.ProjectRoot)
				if err != nil {
					return err
				}
				moduleDir := filepath.Join(eventBusTransportRoot(root), name.Package)
				if _, err := os.Stat(filepath.Dir(moduleDir)); err != nil {
					if os.IsNotExist(err) {
						return fmt.Errorf("eventbus is not initialized; run eventbus init first")
					}
					return fmt.Errorf("inspect eventbus transport: %w", err)
				}
				if _, err := os.Stat(moduleDir); err == nil {
					return fmt.Errorf("eventbus module already exists: %s", name.Package)
				} else if !os.IsNotExist(err) {
					return fmt.Errorf("inspect eventbus module: %w", err)
				}

				if err := os.MkdirAll(moduleDir, 0o755); err != nil {
					return fmt.Errorf("create eventbus module directory: %w", err)
				}
				provider := fmt.Sprintf(`%s

				// Package %s contains EventBus transport components for the %s module.
				package %s
				
				import "github.com/google/wire"
				
				// ProviderSet contains the module's EventBus transport providers.
				var ProviderSet = wire.NewSet()
				`, eventBusGeneratedHeader, name.Package, name.Type, name.Package)
				if err := support.WriteNewFile(filepath.Join(moduleDir, "provider.go"), []byte(provider)); err != nil {
					_ = os.RemoveAll(moduleDir)
					return err
				}
				if err := support.WriteNewFile(filepath.Join(moduleDir, eventBusModuleMarker), []byte(name.Package+"\n")); err != nil {
					_ = os.RemoveAll(moduleDir)
					return err
				}
				if err := c.writeEventBusRegistration(root); err != nil {
					_ = os.RemoveAll(moduleDir)
					return err
				}
				fmt.Fprintf(cmd.OutOrStdout(), "eventbus module created: %s\n", name.Package)
				return nil
			},
		},
		&cobra.Command{
			Use:   "list",
			Short: "List generated EventBus transport modules",
			Args:  cobra.NoArgs,
			RunE: func(cmd *cobra.Command, _ []string) error {
				root, err := support.ProjectRoot(c.ProjectRoot)
				if err != nil {
					return err
				}
				modules, err := eventBusModules(root)
				if err != nil {
					return err
				}
				if len(modules) == 0 {
					fmt.Fprintln(cmd.OutOrStdout(), "no eventbus modules")
					return nil
				}
				for _, module := range modules {
					fmt.Fprintln(cmd.OutOrStdout(), module)
				}
				return nil
			},
		},
		&cobra.Command{
			Use:   "remove <Name>",
			Short: "Remove a generated EventBus transport module",
			Args:  cobra.ExactArgs(1),
			RunE: func(cmd *cobra.Command, args []string) error {
				name, err := support.NormalizeName(args[0])
				if err != nil {
					return err
				}
				root, err := support.ProjectRoot(c.ProjectRoot)
				if err != nil {
					return err
				}
				moduleDir := filepath.Join(eventBusTransportRoot(root), name.Package)
				info, err := os.Lstat(moduleDir)
				if err != nil {
					if os.IsNotExist(err) {
						return fmt.Errorf("eventbus module does not exist: %s", name.Package)
					}
					return fmt.Errorf("inspect eventbus module: %w", err)
				}
				if !info.IsDir() || info.Mode()&os.ModeSymlink != 0 {
					return fmt.Errorf("eventbus module path is not a directory: %s", moduleDir)
				}
				if _, err := os.Stat(filepath.Join(moduleDir, eventBusModuleMarker)); err != nil {
					return fmt.Errorf("refusing to remove unmanaged eventbus module: %s", name.Package)
				}
				if err := requireManagedEventBusRegistration(root); err != nil {
					return err
				}
				if err := os.RemoveAll(moduleDir); err != nil {
					return fmt.Errorf("remove eventbus module %s: %w", name.Package, err)
				}
				if err := c.writeEventBusRegistration(root); err != nil {
					return err
				}
				fmt.Fprintf(cmd.OutOrStdout(), "eventbus module removed: %s\n", name.Package)
				return nil
			},
		},
	)
	return command
}

func eventBusTransportRoot(root string) string {
	return filepath.Join(root, "internal", "transport", "eventbus", "v1")
}

func eventBusModules(root string) ([]string, error) {
	transportRoot := eventBusTransportRoot(root)
	entries, err := os.ReadDir(transportRoot)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, fmt.Errorf("eventbus is not initialized; run eventbus init first")
		}
		return nil, fmt.Errorf("read eventbus modules: %w", err)
	}
	modules := make([]string, 0, len(entries))
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		if _, err := os.Stat(filepath.Join(transportRoot, entry.Name(), eventBusModuleMarker)); err == nil {
			modules = append(modules, entry.Name())
		}
	}
	sort.Strings(modules)
	return modules, nil
}

func (c *EventBusCommand) writeEventBusRegistration(root string) error {
	modules, err := eventBusModules(root)
	if err != nil {
		return err
	}
	module, err := support.ModulePath(root)
	if err != nil {
		return err
	}

	var imports strings.Builder
	var providers strings.Builder
	for _, name := range modules {
		fmt.Fprintf(&imports, "\t%s \"%s/internal/transport/eventbus/v1/%s\"\n", name, module, name)
		fmt.Fprintf(&providers, "\t%s.ProviderSet,\n", name)
	}
	content := fmt.Sprintf(`%s

	// Package v1 composes versioned EventBus transport modules.
	package v1
	
	import (
	%s	"github.com/google/wire"
	)
	
	// ProviderSet contains all generated EventBus transport module providers.
	var ProviderSet = wire.NewSet(
	%s)
	`, eventBusGeneratedHeader, imports.String(), providers.String())
	formatted, err := format.Source([]byte(content))
	if err != nil {
		return fmt.Errorf("format eventbus registration: %w", err)
	}

	path := filepath.Join(eventBusTransportRoot(root), "provider.go")
	if existing, err := os.ReadFile(path); err == nil {
		if !strings.HasPrefix(string(existing), eventBusGeneratedHeader) {
			return fmt.Errorf("refusing to overwrite unmanaged registration file: %s", path)
		}
	} else if !os.IsNotExist(err) {
		return fmt.Errorf("read eventbus registration: %w", err)
	}
	if err := os.WriteFile(path, formatted, 0o644); err != nil {
		return fmt.Errorf("write eventbus registration: %w", err)
	}
	return nil
}

func requireManagedEventBusRegistration(root string) error {
	path := filepath.Join(eventBusTransportRoot(root), "provider.go")
	content, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("read eventbus registration: %w", err)
	}
	if !strings.HasPrefix(string(content), eventBusGeneratedHeader) {
		return fmt.Errorf("refusing to modify unmanaged registration file: %s", path)
	}
	return nil
}
