APP_ENV: prod
SERVICE_NAME: skyrix-framework

LOGGER:
  LOG_OUTPUT: stdout
  LOG_TYPE: json
  LOG_LEVEL: info
  LOG_DIR: ./logs
  LOG_FILE: framework.log

HTTP_SERVER:
  APP_ADDRESS: 0.0.0.0
  APP_PORT: 7540
  APP_REQUEST_TIMEOUT: 5s

DATABASE:
  DB_HOST: postgres
  DB_PORT: 5432
  DB_USER: skyrix
  DB_PASS: change_me
  DB_NAME: skyrix_framework
  DB_MAIN_SCHEMA: public

REDIS:
  REDIS_HOST: redis
  REDIS_PORT: 6379
  REDIS_PASS: ""
  REDIS_DB: 0

JWT:
  JWT_PUBLIC_KEY_PATH: "/run/secrets/jwt/public.pem"
  JWT_EXPIRE: 24
  JWT_ALGORITHM: RS256
  JWT_ISSUER: skyrix-auth
  JWT_AUDIENCE: ""

QUEUE:
  QUEUE_ENABLED: false
  QUEUE_HOST: nats
  QUEUE_PORT: 4222
  QUEUE_NAME: skyrix-framework
  QUEUE_USER: ""
  QUEUE_PASS: ""
  QUEUE_RETRY_TIMEOUT: 5s
  QUEUE_RECONNECT_TIMEOUT: 2s
  DLQ_PREFIX: "dlq."

TENANT_CACHE:
  TENANT_CACHE_TTL: 3m
  TENANT_CACHE_KEY_PREFIX: skyrix-framework
